server:
  port: 7111
  servlet:
    context-path: /ws-app

spring:
  artemis:
    embedded:
      queues: ${app.queue}
    mode: embedded
    host: localhost
    port: 61611
    user: admin
    password: admin

camel:
  component:
    servlet:
      mapping:
        context-path: /*

app:
  queue:
    receive: receiveQueue
    produce: produceQueue
